name: Lint PR

on: [pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1   
      - run: npm ci
      - name: Lint
        uses: Krizzu/eslint-check-action@v1.0.0
        with:
          ghToken: ${{ secrets.GITHUB_TOKEN }}
          eslintExt: "ts, tsx"
