name: Lint PR

on: [pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: stefanoeb/eslint-action@1.0.0
        with:
          args: './src/**/*.{js,ts,tsx}'
