name: Lint PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:    
    uses: unosquare/bump-npm-version/.github/workflows/lint-pnpm.yml@master
    secrets:
      github-token: ${{ secrets.GPR_ACCESS_TOKEN }}
